DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS theme;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE movie (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT UNIQUE NOT NULL,
	imdb TEXT UNIQUE NOT NULL
);

CREATE TABLE theme (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	spotify NOT NULL,
	movie INTEGER NOT NULL,
	composer NOT NULL,
	FOREIGN KEY (movie) REFERENCES movie (id)
);


